### ISSUE TITLE
Project board and issues label 

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/java-library-glpi#1]
Hi, @Naylin15    

Could you prepare project board and the label of the issues.

Two Projects

* Website
* Library

Thanks.

**Comment by Naylin15** [comment]
Hi, @ajsb85 

This is done 

![Project Board](https://user-images.githubusercontent.com/30867977/33087050-dcab625c-cebf-11e7-8f5f-5cbdbba827dc.png)
