### ISSUE TITLE
Documentation for the examples

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/java-library-glpi#18]
Hi, @Naylin15 

Could you add a README.md file in the example folder with the information about how to install and run the example?

Thanks

**Comment by ajsb85** [comment]
Hi, @rafaelje 

I want to debug the Test app.

I added this filter:

`adb -d logcat org.flyve.glpiproject:I *:S `

Could you provide the documentation to debug the app in this issue?

Thanks.

**Comment by ajsb85** [comment]
Hi, @rafaelje Could you help me with the debug of the test app?

**Comment by rafaelje** [comment]
@ajsb85 Off course please let me know what do you need or when we can talk

**Comment by rafaelje** [comment]
This is the better way to show logs:

`adb shell logcat | grep -E "org.glpi.api"`

**Comment by ajsb85** [comment]
@rafaelje Thanks

**Comment by ajsb85** [comment]
Hi, @Naylin15 

Could you add the information related to debug the demo app in this section https://git.io/vF7j2

Thank you.

**Comment by ajsb85** [comment]
The information is also present in the README file of the demo app
https://git.io/vF7j6
Could you @Naylin15  improve this README file?
