### ISSUE TITLE
Client API REST for GLPI 

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/java-library-glpi#2]
Hi, @rafaelje  

This is the main task, create the Gradle plugin for the GLPI API REST.
Generic for any project in the future.

This is an example.
https://github.com/google/google-api-java-client/
https://developers.google.com/api-client-library/java/

- [x]  killSession
- [x]  getMyProfiles
- [x]  getActiveProfile
- [x]  changeActiveProfile
- [x]  getMyEntities
- [x]  getActiveEntities
- [x]  changeActiveEntities
- [x]  getFullSession
- [x]  getAnItem
- [x]  getAllItems
- [x]  getSubItems
- [x]  getMultipleItems
- [x]  listSearchOptions
- [x]  searchItems
- [x]  addItem
- [x]  addItems
- [x]  lostPassword
- [x]  updateItem
- [x]  updateItems
- [x]  deleteItem
- [x]  deleteItems

**Comment by ajsb85** [comment]
Hi, @rafaelje  

Please check the features completed and finish asap the remaining features of the last workshop

- [ ] killSession
- [ ] getMyProfiles
- [ ] getActiveProfile
- [ ] changeActiveProfile
- [ ] getMyEntities
- [ ] getActiveEntities
- [ ] changeActiveEntities
- [ ] getFullSession
- [ ] getAnItem
- [ ] getAllItems
- [ ] getSubItems
- [ ] getMultipleItems
- [ ] listSearchOptions
- [ ] searchItems
- [ ] addItem
- [ ] addItems
- [ ] lostPassword
- [ ] updateItem
- [ ] updateItems
- [ ] deleteItem
- [ ] deleteItems

**Comment by rafaelje** [comment]
- [x]  killSession
- [x]  getMyProfiles
- [x]  getActiveProfile
- [x]  changeActiveProfile
- [x]  getMyEntities
- [x]  getActiveEntities
- [x]  changeActiveEntities
- [x]  getFullSession
- [x]  getAnItem
- [x]  getAllItems
- [x]  getSubItems
- [ ]  getMultipleItems
- [ ]  listSearchOptions
- [ ]  searchItems
- [x]  addItem
- [x]  addItems
- [x]  lostPassword
- [x]  updateItem
- [x]  updateItems
- [x]  deleteItem
- [x]  deleteItems

**Comment by Ivans51** [comment]
- [x]  killSession
- [x]  getMyProfiles
- [x]  getActiveProfile
- [x]  changeActiveProfile
- [x]  getMyEntities
- [x]  getActiveEntities
- [x]  changeActiveEntities
- [x]  getFullSession
- [x]  getAnItem
- [x]  getAllItems
- [x]  getSubItems
- [ ]  getMultipleItems
- [ ]  listSearchOptions
- [ ]  searchItems
- [x]  addItem
- [x]  addItems
- [x]  lostPassword
- [x]  updateItem
- [x]  updateItems
- [x]  deleteItem
- [x]  deleteItems

**Comment by Ivans51** [comment]
Checklist completed, I close it.
