### ISSUE TITLE
Parameters (query string) for Get An Item endpoint

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/java-library-glpi#22]
Hi, @rafaelje

Could you add support in the library for these options?

Parameters: (query string)

- [ ] id: unique identifier of the itemtype. Mandatory.
- [ ] expand_dropdowns (default: false): show dropdown name instead of id. Optional.
- [ ] get_hateoas (default: true): Show relations of the item in a links attribute. Optional.
- [ ] get_sha1 (default: false): Get a sha1 signature instead of the full answer. Optional.
- [ ] with_devices: Only for [Computer, NetworkEquipment, Peripheral, Phone, Printer], retrieve the associated components. Optional.
- [ ] with_disks: Only for Computer, retrieve the associated file-systems. Optional.
- [ ] with_softwares: Only for Computer, retrieve the associated software's installations. Optional.
- [ ] with_connections: Only for Computer, retrieve the associated direct connections (like peripherals and printers) .Optional.
- [ ] with_networkports: Retrieve all network's connections and advanced network's informations. Optional.
- [ ] with_infocoms: Retrieve financial and administrative informations. Optional.
- [ ] with_contracts: Retrieve associated contracts. Optional.
- [ ] with_documents: Retrieve associated external documents. Optional.
- [ ] with_tickets: Retrieve associated itil tickets. Optional.
- [ ] with_problems: Retrieve associated itil problems. Optional.
- [ ] with_changes: Retrieve associated itil changes. Optional.
- [ ] with_notes: Retrieve Notes. Optional.
- [ ] with_logs: Retrieve historical. Optional.

**Comment by ajsb85** [comment]
This is an example how I manage these options https://git.io/vFJv3

**Comment by rafaelje** [comment]
Hi @ajsb85 this feature is ready but is not implemented in the example app
