### ISSUE TITLE
Wiki article per API method

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/java-library-glpi#27]
Hi, @Naylin15 

Please, write an article per each method of the library (https://prose.io).
Try to use common name and information for all the libraries and report issues related to missed or different information with other libraries. 

/cc @rafaelje

**Comment by ajsb85** [comment]
Hi, @rafaelje 

Could you write a draft per method similar to this example?
https://github.com/flyve-mdm/flyve-mdm-android-inventory#java

So, @Naylin15 can improve the description and content later.

Thanks.

**Comment by Naylin15** [comment]
Hi, @ajsb85 

This is done in #39
