### ISSUE TITLE
Project Site Issues

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/java-library-glpi#31]
Hi, @Gianfranco97 

I will report here all issues related to the Website of the repository.

**Comment by ajsb85** [comment]
Green (Flyve MDM) buttons instead blue (GLPI Network)

URL reference: https://glpi-project.github.io/java-library-glpi/reports/javadoc/org/flyve/glpi/GLPI.initSessionCallback.html

![image](https://user-images.githubusercontent.com/663460/32100983-6d818968-bb16-11e7-8246-7b8776cc9ff1.png)

**Comment by ajsb85** [comment]
Test reports in green colors (Flyve MDM) instead blue (GLPI Network)

URL Reference: https://glpi-project.github.io/java-library-glpi/reports/androidTests/connected/

![image](https://user-images.githubusercontent.com/663460/32101029-b1e02e70-bb16-11e7-806c-76d35ba5ba72.png)

**Comment by ajsb85** [comment]
Contact information about Flyve MDM instead GLPI.

URL: https://glpi-project.github.io/java-library-glpi/contact

**Comment by Gianfranco97** [comment]
![screenshot-2017-10-27 java library glpi](https://user-images.githubusercontent.com/19965590/32112885-8ceb8f38-bb0c-11e7-8787-30f7b84ecfa6.png)



![screenshot-2017-10-27 java library glpi 1](https://user-images.githubusercontent.com/19965590/32112886-8d0c1640-bb0c-11e7-995d-c6da05c4c86a.png)



![screenshot-2017-10-27 java library glpi 2](https://user-images.githubusercontent.com/19965590/32112887-8d284004-bb0c-11e7-955e-8c473ce4006b.png)

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Could you replace the contact information of Flyve MDM and use the GLPI.
https://glpi-project.github.io/java-library-glpi/contact

Thanks.

**Comment by Gianfranco97** [comment]
@ajsb85. I think that is already done, but I still have not made the PR.
Let me solution the conflicts of git stories and I make the PR.
