### ISSUE TITLE
HTTP requests File location

### ISSUE THREAD

**Issue by mamunmohamed** [glpi-project/java-library-glpi#47]
Hello my name is Mamun. I'm looking for the file where the HTTP requests are. Could someone help me find it?
Thank you

**Comment by rafaelje** [comment]
Hello @mamunmohamed this library is using retrofit2 to create the HTTP Request and require a .env file for configuration this project is still in develop

**Comment by antrix190** [comment]
Is there something left to be done in this issue?

**Comment by mamunmohamed** [comment]
I didn't continued it. Because I don't found the file.

**Comment by Ivans51** [comment]
Hi @mamunmohamed
Here you have the base URL https://github.com/glpi-project/java-library-glpi/blob/develop/glpi/src/main/java/org/glpi/api/ServiceGenerator.java

and here the list of the requests https://github.com/glpi-project/java-library-glpi/blob/develop/glpi/src/main/java/org/glpi/api/Routes.java

**Comment by Ivans51** [comment]
I will close this issue
